### ISSUE TITLE
Use CI to weave notebooks?

### ISSUE THREAD

**Issue by dlfivefifty** [Imperial-MATH50003/MATH50003NumericalAnalysis#1]
@MikaelSlevinsky do you know if it's easy to get Github Actions to automatically "weave" notebooks on push, that is, run the following:
```julia
kwds = (out_path="notebooks/", jupyter_path="$(homedir())/.julia/conda/3/bin/jupyter", nbconvert_options="--allow-errors")

notebook("src/Julia.jmd"; kwds...)
```
There seems to be two issues:

1. I'm not sure running `jupyter` is possible
2. Would it require an extra git push for every push?

**Comment by MikaelSlevinsky** [comment]
Kinda sounds like making docs? Can git force push hard to a dedicated branch, with permalinks to that branch.

As for running jupyter, it may be a question of first checking python deps. I seem to recall this was considered on one class of CIs but I'm not sure if it was the GitHub actions.

**Comment by dlfivefifty** [comment]
Yeah that’s what I’m thinking, do whatever Documenter does but with Jupyter notebooks
