### ISSUE TITLE
Clarification for Week 2, Problem 1.2

### ISSUE THREAD

**Issue by TSGut** [Imperial-MATH50003/MATH50003NumericalAnalysis#10]
Problem 1.2 for Week 2's problem sheet currently reads

```
Implement central differences for $f(x) = 1 + x + x^2$ and $g(x) = 1 + x/3 + x^2$. 
Plot the errors. 
Derive the error exactly for the different cases to explain the observed behaviour.
```

It may be helpful to be more clear on what exactly one is expected to plot. I assume what is meant is choose an arbitrary 'x' and plot the error as it varies with 'h' in a similar way to what was done in the lectures - is that correct?

**Comment by dlfivefifty** [comment]
Yes correct. Maybe we say with powers of 2 and powers of 10

**Comment by TSGut** [comment]
I think you fixed this with https://github.com/Imperial-MATH50003/MATH50003NumericalAnalysis/commit/0bc6fff2ea0ea6401c6e5ee5d14b4ea876132a31 so I will close this issue.
