### ISSUE TITLE
Mid term and practice mid term dates

### ISSUE THREAD

**Issue by TSGut** [Imperial-MATH50003/MATH50003NumericalAnalysis#3]
The practice mid-term is currently stated to occur after the mid-term in the Readme, see

https://github.com/Imperial-MATH50003/MATH50003NumericalAnalysis/blob/a2b883d41cd16673f3f9157409c4ef65570b7688/README.md?plain=1#L41

Did the dates get swapped?

**Comment by dlfivefifty** [comment]
Fixed (plus updated dates)
