### ISSUE TITLE
How to type ⋰ in notebook?

### ISSUE THREAD

**Issue by putianyi889** [Imperial-MATH50003/MATH50003NumericalAnalysis#44]
pasting the unicode character can work but it isn't rendered properly compared to `\ddots`. I've tried `\iddots`, `\udots` and `\adots` but they are not included by the notebook.

**Comment by dlfivefifty** [comment]
I don't know. Just copy-and-paste?

**Comment by TSGut** [comment]
I don't think that symbol can be written in LaTeX without use of packages or custom reflections so just write \text{⋰} or something of that sort.
